// <auto-generated />
using System;
using BlogProject.Data.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogProject.Data.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("BlogProject.Entities.Concrete.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SeoAuthor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SeoTags")
                        .HasColumnType("text");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WievsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CommentCount = 1,
                            Content = "The future of civilization rests in the fate of the One Ring, which has been lost for centuries. Powerful forces are unrelenting in their search for it. But fate has placed it in the hands of a young Hobbit named Frodo Baggins, who inherits the Ring and steps into legend. A daunting task lies ahead for Frodo when he becomes the Ringbearer to destroy the One Ring in the fires of Mount Doom where it was forged.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(4180),
                            Date = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(2320),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(4590),
                            Note = "About Lord Of The Lord of the Rings: The Fellowship of the Ring Novel",
                            SeoAuthor = "Kutlu Özdemir",
                            SeoDescription = "About Lord Of The Lord of the Rings: The Fellowship of the Ring Novel",
                            SeoTags = "Lord Of The Lord of the Rings, Epic Fantasy, Novel, Tolkien",
                            Thumbnail = "postImages/defaultThumbnail.jpg",
                            Title = "Lord Of The Lord of the Rings: The Fellowship of the Ring",
                            UserId = 1,
                            WievsCount = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CommentCount = 1,
                            Content = "When astronauts blast off from the planet Mars, they leave behind Mark Watney, presumed dead after a fierce storm. With only a meager amount of supplies, the stranded visitor must utilize his wits and spirit to find a way to survive on the hostile planet. Meanwhile, back on Earth, members of NASA and a team of international scientists work tirelessly to bring him home, while his crew mates hatch their own plan for a daring rescue mission.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6360),
                            Date = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6350),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6360),
                            Note = "About The Martian Novel",
                            SeoAuthor = "Kutlu Özdemir",
                            SeoDescription = "About The Martian Novel",
                            SeoTags = "The Martian, Science Fiction, Novel, Andy Weir",
                            Thumbnail = "postImages/defaultThumbnail.jpg",
                            Title = "The Martian",
                            UserId = 1,
                            WievsCount = 10
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CommentCount = 1,
                            Content = "In the tenth arrondissement of Paris, a rookie police inspector and a seasoned veteran called out of retirement investigate the horrific murders of three anonymous young women, illegal Turkish aliens who could not have deserved such a brutal, inhuman death.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6370),
                            Date = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6360),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6370),
                            Note = "About The Empire of the Wolves Novel",
                            SeoAuthor = "Kutlu Özdemir",
                            SeoDescription = "About The Empire of the Wolves Novel",
                            SeoTags = "The Empire of the Wolves, Detective Thriller, Novel, Jean-Christophe Grange",
                            Thumbnail = "postImages/defaultThumbnail.jpg",
                            Title = "The Empire of the Wolves",
                            UserId = 1,
                            WievsCount = 10
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CommentCount = 1,
                            Content = "The Fault in Our Stars is a novel about love and death. The main character, Hazel, is a young woman who has been battling thyroid cancer for years. At a cancer support meeting, she meets Augustus, a young man who is recovering from cancer. He helps her break out of her shell and see the bright side of life.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6370),
                            Date = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6370),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6380),
                            Note = "About The Fault in Our Stars Novel",
                            SeoAuthor = "Kutlu Özdemir",
                            SeoDescription = "About The Fault in Our Stars Novel",
                            SeoTags = "The Fault in Our Stars, Emotional, Novel, John Green",
                            Thumbnail = "postImages/defaultThumbnail.jpg",
                            Title = "The Fault in Our Stars",
                            UserId = 1,
                            WievsCount = 10
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CommentCount = 1,
                            Content = "The Notebook is an achingly tender story about the enduring power of love, a story of miracles that will stay with you forever. Set amid the austere beauty of coastal North Carolina in 1946, The Notebook begins with the story of Noah Calhoun, a rural Southerner returned home from World War II.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6380),
                            Date = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6380),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6380),
                            Note = "About The Notebook Novel",
                            SeoAuthor = "Kutlu Özdemir",
                            SeoDescription = "About The Notebook",
                            SeoTags = "The Notebook, Romantic, Novel, Nicholas Sparks",
                            Thumbnail = "postImages/defaultThumbnail.jpg",
                            Title = "The Notebook",
                            UserId = 1,
                            WievsCount = 10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CommentCount = 1,
                            Content = "It is a 1986 horror novel by American author Stephen King. It was his 22nd book and his 17th novel written under his own name. The story follows the experiences of seven children as they are terrorized by an evil entity that exploits the fears of its victims to disguise itself while hunting its prey.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6390),
                            Date = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6390),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6390),
                            Note = "About The IT Novel",
                            SeoAuthor = "Kutlu Özdemir",
                            SeoDescription = "About The IT Novel",
                            SeoTags = "IT, Horror, Novel, Stephen King",
                            Thumbnail = "postImages/defaultThumbnail.jpg",
                            Title = "IT",
                            UserId = 1,
                            WievsCount = 10
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CommentCount = 1,
                            Content = "A Tale of Two Cities, by Charles Dickens, deals with the major themes of duality, revolution, and resurrection. It was the best of times, it was the worst of times in London and Paris, as economic and political unrest lead to the American and French Revolutions.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6400),
                            Date = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6400),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6400),
                            Note = "About A Tale of Two Cities Novel",
                            SeoAuthor = "Kutlu Özdemir",
                            SeoDescription = "About A Tale of Two Cities Novel",
                            SeoTags = "A Tale of Two Cities, Historical, Novel, Charles Dickens",
                            Thumbnail = "postImages/defaultThumbnail.jpg",
                            Title = "A Tale of Two Cities",
                            UserId = 1,
                            WievsCount = 10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            CommentCount = 1,
                            Content = "In A Modern Utopia, two travelers fall into a space-warp and suddenly find themselves upon a Utopian Earth controlled by a single World Government.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6410),
                            Date = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6410),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6410),
                            Note = "About A Modern Utopia Novel",
                            SeoAuthor = "Kutlu Özdemir",
                            SeoDescription = "About A Modern Utopia Novel",
                            SeoTags = "A Modern Utopia, Utopian, Novel, H. G. Wells",
                            Thumbnail = "postImages/defaultThumbnail.jpg",
                            Title = "A Modern Utopia",
                            UserId = 1,
                            WievsCount = 10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            CommentCount = 1,
                            Content = "The novel explores an alternative religious history, whose central plot point is that the Merovingian kings of France were descended from the bloodline of Jesus Christ and Mary Magdalene, ideas derived from Clive Prince's The Templar Revelation (1997) and books by Margaret Starbird.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6420),
                            Date = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6420),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6420),
                            Note = "About The Da Vinci Code Novel",
                            SeoAuthor = "Kutlu Özdemir",
                            SeoDescription = "About The Da Vinci Code Novel",
                            SeoTags = "The Da Vinci Code, Mistery, Novel, Dan Brown",
                            Thumbnail = "postImages/defaultThumbnail.jpg",
                            Title = "The Da Vinci Code",
                            UserId = 1,
                            WievsCount = 10
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            CommentCount = 1,
                            Content = "When astronauts blast off from the planet Mars, they leave behind Mark Watney, presumed dead after a fierce storm. With only a meager amount of supplies, the stranded visitor must utilize his wits and spirit to find a way to survive on the hostile planet. Meanwhile, back on Earth, members of NASA and a team of international scientists work tirelessly to bring him home, while his crew mates hatch their own plan for a daring rescue mission.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6430),
                            Date = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6420),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 584, DateTimeKind.Local).AddTicks(6430),
                            Note = "About Frankenstein Novel",
                            SeoAuthor = "Kutlu Özdemir",
                            SeoDescription = "About Frankenstein Novel",
                            SeoTags = "Frankenstein, Gothic, Novel, Mary Shelley",
                            Thumbnail = "postImages/defaultThumbnail.jpg",
                            Title = "Frankenstein",
                            UserId = 1,
                            WievsCount = 10
                        });
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6740),
                            Description = "Blogs About Epic Fantasy Novels",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6750),
                            Name = "Epic Fantasy",
                            Note = "Epic Fantasy Novels"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6770),
                            Description = "Blogs About Science Fiction Novels",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6770),
                            Name = "Science Fiction",
                            Note = "Science Fiction Novels"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6780),
                            Description = "Blogs About Detective Thriller Novels",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6780),
                            Name = "Detective Thriller",
                            Note = "Detective Thriller Novels"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6780),
                            Description = "Blogs About Emotional Novels",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6780),
                            Name = "Emotional",
                            Note = "Emotional Novels"
                        },
                        new
                        {
                            Id = 5,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6790),
                            Description = "Blogs About Romantic Novels",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6790),
                            Name = "Romantic",
                            Note = "Romantic Novels"
                        },
                        new
                        {
                            Id = 6,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6800),
                            Description = "Blogs About Horror Novels",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6800),
                            Name = "Horror",
                            Note = "Horror Novels"
                        },
                        new
                        {
                            Id = 7,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6800),
                            Description = "Blogs About Historical Novels",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6800),
                            Name = "Historical",
                            Note = "Historical Novels"
                        },
                        new
                        {
                            Id = 8,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6810),
                            Description = "Blogs About Utopian Novels",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6810),
                            Name = "Utopian",
                            Note = "Utopian Novels"
                        },
                        new
                        {
                            Id = 9,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6820),
                            Description = "Blogs About Mistery Novels",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6820),
                            Name = "Mistery",
                            Note = "Mistery Novels"
                        },
                        new
                        {
                            Id = 10,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6820),
                            Description = "Blogs About Gothic Novels",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 588, DateTimeKind.Local).AddTicks(6830),
                            Name = "Gothic",
                            Note = "Gothic Novels"
                        });
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6460),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6470),
                            Note = "Comment About Lord Of The Lord of the Rings: The Fellowship of the Ring Novel",
                            Text = "This is the best thing I have ever read."
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6490),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6490),
                            Note = "Comment About The Martian Novel",
                            Text = "This novel take my breath away when i was reading"
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6500),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6500),
                            Note = "Comment About The Empire of the Wolves Novel",
                            Text = "It has been years since I read this book but I still remember the plot and characters in detail. This book started off very interesting for me; the main character suffers from partial amnesia, she forgets his husbands face but no-one elses. I was instantly pulled in and could not put this book down first. Writing is graphic and detailed, which I enjoyed. Too bad the ending was, in my opinion, terrible. I want to like this book more than I do, this had so much potential but the ending was boring and and at parts the plot went on relying too much on coincidence. Still, I enjoyed the beginning of this mystery very much."
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 4,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6500),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6510),
                            Note = "Comment About The Fault in Our Stars Novel",
                            Text = "I was unable to build any kind of connection to the characters. A lot of their actions seemed immature and childish to me. The main character is constantly saying how she wants everyone to treat her like a normal kid, but it's hard when she's constantly reminding you that she is dying, not reminding you that she has cancer and working through it, but that she is dying and that everything that is happening to her, is because she is dying..."
                        },
                        new
                        {
                            Id = 5,
                            ArticleId = 5,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6510),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6510),
                            Note = "Comment About The Notebook Novel",
                            Text = "Does such true love really exist? Nicholas Sparks, all I can tell is that your wife Cathy has been lucky to marry you!I cried like a baby.Yes, true love will return to you, maybe not in a very perfect condition, maybe with a fiancee, maybe not with a good heart, but surely it'll return."
                        },
                        new
                        {
                            Id = 6,
                            ArticleId = 6,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6520),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6520),
                            Note = "Comment About IT Novel",
                            Text = "Why yes, I did just complete my longest read to date. I simultaneously feel relieved and accomplished, drained and fulfilled. There are few authors who can successfully deliver such conflicting feelings, which is why he's one of the most well known names in the fiction world. I feel as if I could write an entire book about this tender and terrifying coming of age tale, but I also feel as if all the umph has left my body for the moment. Definitely my favorite King novel that I've read so far and I hope to revisit this review after a time of processing and reflection to add more thoughts. Thanks for all the hand holding and encouragement you all provided along the way!"
                        },
                        new
                        {
                            Id = 7,
                            ArticleId = 7,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6520),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6530),
                            Note = "Comment About A Tale of Two Cities Novel",
                            Text = "A wonderful fact to reflect upon, that every human creature is constituted to be that profound secret and mystery to every other. A solemn consideration, when I enter a great city by night, that every one of those darkly clustered houses encloses its own secret; that every room in every one of them encloses its own secret; that every beating heart in the hundreds of thousands of breasts there, is, in some of its imaginings, a secret to the heart nearest it!"
                        },
                        new
                        {
                            Id = 8,
                            ArticleId = 8,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6530),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6530),
                            Note = "Comment About A Modern Utopia Novel",
                            Text = "3 rating is like a neutral rating. This is a difficult book to get through but it might be of great use to students in social science and philosophy to understand the strength and weakness of some of the theories. One needs to be familiar with names like plato, aristotle, th more, Aquinas, comte, rousseau, marx.. Questions about social order, women place, political practice, religion (despite its contribution to equality) and culture problems are discussed but not solved, leaving the world at the starting point as we can easily see many years after the book was written!"
                        },
                        new
                        {
                            Id = 9,
                            ArticleId = 9,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6540),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6540),
                            Note = "Comment About The Da Vinci Code Novel",
                            Text = "For the most part, it seems that people either passionately love this book or they passionately hate it. I happen to be one of the former. For my part, I don't see the book so much as an indictment of the Catholic Church in particular but of religious extremism and religion interfering in political process in general. The unwarranted political control granted to extreme religious organizations like the CBN is an issue that we will be forced to address one way or the other. To my eye, our political process has been poisoned by it and the danger of theocracy is quite real. Furthermore, Brown's indictment of the Church for removing or suppressing feminine divinity figures is justified and needs a much closer look. Women do not have enough of a role in religion, religious practice, heroic myths, and creation myths, nor are they portrayed as divinity figures enough. In short, our religious systems and institutions lack balance and have a bias to suppress issues, stories, and roles that empower women to live as equals to men. Finally, Brown wrote his story simplistically, in my view, to spread his tale to as broad an audience as possible. Though it is not as pristine a narrative as, say, Umberto Eco, the message it conveys is one that needs to be heard. More obscure books on the matter are not as accessible as Da Vinci Code and if someone were to write an accessible book of genius on this subject, I would give him/her all due praise. In the meantime, Dan Brown is telling a story that needs to be told. It is one that has been kept quiet and in the dark for far too long."
                        },
                        new
                        {
                            Id = 10,
                            ArticleId = 10,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6540),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 6, 3, 17, 7, 55, 591, DateTimeKind.Local).AddTicks(6540),
                            Note = "Comment About Frankenstein Novel",
                            Text = "This is another book that i read in high school, but greatly appreciated it, even at that age. As a fan of comparing movie adaptions to books, I remember thinking ‘this is a hell of a lot different than the frankenstein that I knew.’ For one, the monster’s name isn’t Frankenstein, and he wasn’t just a mindless drone stumbling around. He was a highly intelligent, agile, and emotional creature. The film version with Robert Deniro was by far the most accurate, although not totally, depiction from what I remember, but it wasn’t widely acclaimed. This is still a very scary book and an absolute staple in horror literature. But the emotions of the monster were what I remember the most. From his admission to killing Victor’s brother and asking for forgiveness, to asking for the creation of a mate, his rage towards his creator, and just the back and forth dynamic between the monster and Victor was the highlight of the novel. The ending was very sad, but utterly satisfactory to this tale. Again, if you are a fan of horror, this is an absolute must read."
                        });
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "a72ea102-a6ec-451d-b100-27bf35329180",
                            Name = "Category.Create",
                            NormalizedName = "CATEGORY.CREATE"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "f9012897-6982-4602-96c9-dedf7d3902f0",
                            Name = "Category.Read",
                            NormalizedName = "CATEGORY.READ"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "f9704330-58f0-4a2d-80ab-ac6783e5c8b1",
                            Name = "Category.Update",
                            NormalizedName = "CATEGORY.UPDATE"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "2d55863f-11a6-44d2-a911-4f208b01761a",
                            Name = "Category.Delete",
                            NormalizedName = "CATEGORY.DELETE"
                        },
                        new
                        {
                            Id = 5,
                            ConcurrencyStamp = "01b8c04f-f834-4887-b3aa-8b953321d8ad",
                            Name = "Article.Create",
                            NormalizedName = "ARTICLE.CREATE"
                        },
                        new
                        {
                            Id = 6,
                            ConcurrencyStamp = "7c752695-ea5e-4771-9881-97e5b42319b7",
                            Name = "Article.Read",
                            NormalizedName = "ARTICLE.READ"
                        },
                        new
                        {
                            Id = 7,
                            ConcurrencyStamp = "c3aacdac-3ed5-4e23-ba43-89102ca13dbe",
                            Name = "Article.Update",
                            NormalizedName = "ARTICLE.UPDATE"
                        },
                        new
                        {
                            Id = 8,
                            ConcurrencyStamp = "dd95b383-d893-4b5f-bdd7-c0643844ac06",
                            Name = "Article.Delete",
                            NormalizedName = "ARTICLE.DELETE"
                        },
                        new
                        {
                            Id = 9,
                            ConcurrencyStamp = "c475a94c-281b-4d6b-960e-5a238c42558e",
                            Name = "User.Create",
                            NormalizedName = "USER.CREATE"
                        },
                        new
                        {
                            Id = 10,
                            ConcurrencyStamp = "d2d650ef-0e2d-460b-8da4-bfddb2be1e84",
                            Name = "User.Read",
                            NormalizedName = "USER.READ"
                        },
                        new
                        {
                            Id = 11,
                            ConcurrencyStamp = "f36e50ff-e15b-4910-a606-98677349c119",
                            Name = "User.Update",
                            NormalizedName = "USER.UPDATE"
                        },
                        new
                        {
                            Id = 12,
                            ConcurrencyStamp = "0522a119-ea29-4200-b1a6-441e0642e6d6",
                            Name = "User.Delete",
                            NormalizedName = "USER.DELETE"
                        },
                        new
                        {
                            Id = 13,
                            ConcurrencyStamp = "11966fcc-c942-4b4c-9bee-9ce48953e122",
                            Name = "Role.Create",
                            NormalizedName = "ROLE.CREATE"
                        },
                        new
                        {
                            Id = 14,
                            ConcurrencyStamp = "40353775-2e8f-4b49-928e-c5ada9d38dd8",
                            Name = "Role.Read",
                            NormalizedName = "ROLE.READ"
                        },
                        new
                        {
                            Id = 15,
                            ConcurrencyStamp = "868e6cf4-b89f-4ef3-bf43-c77a1cadf66a",
                            Name = "Role.Update",
                            NormalizedName = "ROLE.UPDATE"
                        },
                        new
                        {
                            Id = 16,
                            ConcurrencyStamp = "f7b695a0-5f4f-4528-90c9-cbdfc489f863",
                            Name = "Role.Delete",
                            NormalizedName = "ROLE.DELETE"
                        },
                        new
                        {
                            Id = 17,
                            ConcurrencyStamp = "571b777e-2789-4715-87b3-5e5819aea79d",
                            Name = "Comment.Create",
                            NormalizedName = "COMMENT.CREATE"
                        },
                        new
                        {
                            Id = 18,
                            ConcurrencyStamp = "a8e31266-67c3-486d-a349-ea7e4138465a",
                            Name = "Comment.Read",
                            NormalizedName = "COMMENT.READ"
                        },
                        new
                        {
                            Id = 19,
                            ConcurrencyStamp = "298e3dce-d30e-4248-8320-3c0ad03f7f3a",
                            Name = "Comment.Update",
                            NormalizedName = "COMMENT.UPDATE"
                        },
                        new
                        {
                            Id = 20,
                            ConcurrencyStamp = "ab70bd3a-b50f-4489-bdea-bf128bc4aac5",
                            Name = "Comment.Delete",
                            NormalizedName = "COMMENT.DELETE"
                        },
                        new
                        {
                            Id = 21,
                            ConcurrencyStamp = "64243a74-3294-4128-8a76-ebce62a1b978",
                            Name = "AdminArea.Home.Read",
                            NormalizedName = "ADMINAREA.HOME.READ"
                        },
                        new
                        {
                            Id = 22,
                            ConcurrencyStamp = "10d5d24c-9cc8-45c0-92e2-a1d177cf896c",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("About")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FacebookLink")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("GitHubLink")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("InstagramLink")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LinkedInLink")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TwitterLink")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WebsiteLink")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("YoutubeLink")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Admin User of ProgrammersBlog",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bda701b1-85e8-41bb-b191-eddb47a8d53c",
                            Email = "adminuser@gmail.com",
                            EmailConfirmed = true,
                            FacebookLink = "https://facebook.com/adminuser",
                            FirstName = "Kutlu",
                            GitHubLink = "https://github.com/adminuser",
                            InstagramLink = "https://instagram.com/adminuser",
                            LastName = "Özdemir",
                            LinkedInLink = "https://linkedin.com/adminuser",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINUSER@GMAIL.COM",
                            NormalizedUserName = "ADMINUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEJQ6GtnhQSwMDVbisBk3JH0upesEIriocGoBeR7MxYDDyk5dIDr2nZ4G2+/7UGlfZQ==",
                            PhoneNumber = "+905417415083",
                            PhoneNumberConfirmed = true,
                            Picture = "userImages/defaultUser.png",
                            SecurityStamp = "53c36dc1-145f-44cf-b0a7-600a51d3c2d3",
                            TwitterLink = "https://twitter.com/adminuser",
                            TwoFactorEnabled = false,
                            UserName = "adminuser",
                            WebsiteLink = "https://programmersblog.com/",
                            YoutubeLink = "https://youtube.com/adminuser"
                        },
                        new
                        {
                            Id = 2,
                            About = "Editor User of ProgrammersBlog",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46245f9c-7877-4865-9634-4aed4a6e1e5f",
                            Email = "editoruser@gmail.com",
                            EmailConfirmed = true,
                            FacebookLink = "https://facebook.com/editoruser",
                            FirstName = "Bahadır",
                            GitHubLink = "https://github.com/editoruser",
                            InstagramLink = "https://instagram.com/editoruser",
                            LastName = "Özdemir",
                            LinkedInLink = "https://linkedin.com/editoruser",
                            LockoutEnabled = false,
                            NormalizedEmail = "EDITORUSER@GMAIL.COM",
                            NormalizedUserName = "EDITORUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEDpMjZxooaAhP0IGl4YPwe/6NLkMmEsYEikBfIlidoGyqDKckFf9wfarea5eCyeJBg==",
                            PhoneNumber = "+905437348733",
                            PhoneNumberConfirmed = true,
                            Picture = "userImages/defaultUser.png",
                            SecurityStamp = "c598b97b-175e-4c4c-a49f-99a7f7e84ff7",
                            TwitterLink = "https://twitter.com/editoruser",
                            TwoFactorEnabled = false,
                            UserName = "editoruser",
                            WebsiteLink = "https://programmersblog.com/",
                            YoutubeLink = "https://youtube.com/editoruser"
                        });
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 6
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 7
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 8
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 9
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 10
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 11
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 12
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 13
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 14
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 15
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 16
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 17
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 18
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 19
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 20
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 21
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 22
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 6
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 7
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 8
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 17
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 18
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 19
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 20
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 21
                        });
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.Article", b =>
                {
                    b.HasOne("BlogProject.Entities.Concrete.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogProject.Entities.Concrete.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("BlogProject.Entities.Concrete.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.RoleClaim", b =>
                {
                    b.HasOne("BlogProject.Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.UserClaim", b =>
                {
                    b.HasOne("BlogProject.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.UserLogin", b =>
                {
                    b.HasOne("BlogProject.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.UserRole", b =>
                {
                    b.HasOne("BlogProject.Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogProject.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.UserToken", b =>
                {
                    b.HasOne("BlogProject.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("BlogProject.Entities.Concrete.User", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
